apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  name: secretagentconfigurations.secret-agent.secrets.forgerock.io
spec:
  group: secret-agent.secrets.forgerock.io
  names:
    kind: SecretAgentConfiguration
    listKind: SecretAgentConfigurationList
    plural: secretagentconfigurations
    shortNames:
    - sac
    singular: secretagentconfiguration
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: SAC State
      jsonPath: .status.state
      name: Status
      type: string
    - description: Total no. of secrets managed by the sac
      jsonPath: .status.totalManagedSecrets
      name: NumSecrets
      type: integer
    - description: Total no. of k8s secrets created
      jsonPath: .status.totalKubeSecrets
      name: NumK8sSecrets
      type: integer
    - description: Total no. of SM secrets created
      jsonPath: .status.totalSecretManagerSecrets
      name: NumSMSecrets
      priority: 1
      type: integer
    - description: All K8s managed secrets
      jsonPath: .status.managedKubeSecrets
      name: K8sSecrets
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SecretAgentConfiguration is the Schema for the secretagentconfigurations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecretAgentConfigurationSpec defines the desired state of SecretAgentConfiguration
            properties:
              appConfig:
                description: AppConfig is the configuration for the forgeops-secrets application
                properties:
                  awsRegion:
                    type: string
                  azureVaultName:
                    type: string
                  backOffSecs:
                    default: 2
                    description: Optional backoff time in seconds before retrying secret generation. Defaults to 2
                    type: integer
                  createKubernetesObjects:
                    type: boolean
                  credentialsSecretName:
                    type: string
                  gcpProjectID:
                    type: string
                  maxRetries:
                    default: 3
                    description: Optional number of times the operator will attempt to generate secrets. Defaults to 3
                    type: integer
                  secretTimeout:
                    default: 40
                    description: Optional timeout value to generate a individual secret. Defaults to 40
                    type: integer
                  secretsManager:
                    description: SecretsManager Specifies which cloud secret manager will be used
                    enum:
                    - none
                    - GCP
                    - AWS
                    - Azure
                    type: string
                  secretsManagerPrefix:
                    type: string
                required:
                - createKubernetesObjects
                - secretsManager
                type: object
              secrets:
                items:
                  description: SecretConfig is the configuration for a specific Kubernetes secret
                  properties:
                    keys:
                      items:
                        description: KeyConfig is the configuration for a specific data key
                        properties:
                          name:
                            type: string
                          spec:
                            description: KeySpec is the configuration for each key
                            properties:
                              algorithm:
                                description: AlgorithmType Specifies which keystore algorithm to use
                                enum:
                                - ECDSAWithSHA256
                                - SHA256WithRSA
                                type: string
                              distinguishedName:
                                description: DistinguishedName certificate subject data
                                properties:
                                  commonName:
                                    type: string
                                  country:
                                    items:
                                      type: string
                                    type: array
                                  locality:
                                    items:
                                      type: string
                                    type: array
                                  organization:
                                    items:
                                      type: string
                                    type: array
                                  organizationUnit:
                                    items:
                                      type: string
                                    type: array
                                  postalCode:
                                    items:
                                      type: string
                                    type: array
                                  province:
                                    items:
                                      type: string
                                    type: array
                                  serialNumber:
                                    type: string
                                  streetAddress:
                                    items:
                                      type: string
                                    type: array
                                type: object
                              duration:
                                type: string
                              isBase64:
                                type: boolean
                              keyPassPath:
                                type: string
                              keytoolAliases:
                                items:
                                  description: KeytoolAliasConfig is the configuration for a keystore alias
                                  properties:
                                    args:
                                      items:
                                        type: string
                                      type: array
                                    cmd:
                                      description: KeytoolCmd Specifies the keytool command to use.
                                      enum:
                                      - genkeypair
                                      - genseckey
                                      - importcert
                                      - importpassword
                                      - importkeystore
                                      type: string
                                    isKeyPair:
                                      type: boolean
                                    name:
                                      type: string
                                    sourcePath:
                                      type: string
                                  required:
                                  - cmd
                                  - name
                                  type: object
                                minItems: 1
                                type: array
                              length:
                                type: integer
                              pemFormat:
                                type: boolean
                              sans:
                                items:
                                  type: string
                                type: array
                              selfSigned:
                                type: boolean
                              signedWithPath:
                                type: string
                              storePassPath:
                                type: string
                              storeType:
                                description: StoreType Specifies which keystore store type to use
                                enum:
                                - pkcs12
                                - jceks
                                - jks
                                type: string
                              truststoreImportPaths:
                                items:
                                  type: string
                                type: array
                              useBinaryCharacters:
                                type: boolean
                              value:
                                type: string
                            type: object
                          type:
                            description: KeyConfigType Specifies which key type to use
                            enum:
                            - ca
                            - literal
                            - password
                            - ssh
                            - keyPair
                            - truststore
                            - keytool
                            type: string
                        required:
                        - name
                        - type
                        type: object
                      minItems: 1
                      type: array
                    name:
                      type: string
                  required:
                  - keys
                  - name
                  type: object
                minItems: 1
                type: array
            required:
            - appConfig
            - secrets
            type: object
          status:
            description: SecretAgentConfigurationStatus defines the observed state of SecretAgentConfiguration
            properties:
              managedKubeSecrets:
                items:
                  type: string
                type: array
              managedSecretManagerSecrets:
                items:
                  type: string
                type: array
              state:
                description: SecretAgentConfState is used to keep track of the SAC state
                type: string
              totalKubeSecrets:
                type: integer
              totalManagedSecrets:
                type: integer
              totalSecretManagerSecrets:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

